bitpay/bitcore-wallet-client

lib/credentials.js
package.json

- add check to detect wrong inputs.

add check in fromObj

---

README.md
lib/api.js

This PR contains some minor changes to the client API. Internal functions are now (private) static methods of the `API` class.
Also `#toString` and `#fromString` methods have been removed as `export`/`import` should be the preferred method for dealing with serialization.

Improve readme

---

lib/api.js

listen to reconnect events

---

lib/api.js
package.json

- processTxps if openWallet call getStatus
Fixes https://github.com/bitpay/copay/issues/2679

processTxps also in openWallet

---

README.md
lib/api.js
test/client.js

default bws port is 3232, not 3001
suppress log in mocha test to make it easier output easier to read

default bws port is 3232, not 3001

---

README.md

Fix for https://github.com/bitpay/bitcore-wallet-client/issues/116

sendTxProposal documentation is incomplete

---

lib/api.js
lib/credentials.js
test/client.js

- reuse recreateWallet from importOldCopay

refactor importOldCopay

---

lib/api.js
package.json
test/client.js

fixes https://github.com/bitpay/copay/issues/3238

display full derivation path

---

lib/api.js
package.json
test/client.js

Reverts bitpay/bitcore-wallet-client#144

Revert "display full derivation path"

---

lib/api.js
lib/credentials.js
package.json
test/client.js
test/credentials.js

Reverts bitpay/bitcore-wallet-client#154
so it is not included in bitcore.

Revert "Feat/account"

---

lib/api.js
lib/credentials.js
package.json
test/credentials.js

This PR adapts BWC to explicitly use account 0 on address derivation.

Bump/bwu 1.0.0

---

.travis.yml
test/client.js
test/paypro.js

- Fix error with instantiating a buffer from a bitcore PublicKey
- Fixed test to return buffer as expected
- Added Node.js v4 to travis tests

Fixed tests for Node.js v4 support

---

.travis.yml
package.json

disabled support for node 0.10

update node version

---

lib/api.js
test/client.js

fixes: https://github.com/bitpay/copay/issues/3582

use change address for paypro refund

---

lib/api.js

Fixes https://github.com/bitpay/copay/issues/3864

Do not check if wallet is complete in order to get/save prefs

---

lib/credentials.js
test/client.js
test/credentials.js

In Copay [#3534](https://github.com/bitpay/copay/issues/3534) [#3520](https://github.com/bitpay/copay/issues/3520)

keep the seed imported from mnemonics

---

lib/verifier.js
test/client.js

To reproduce try updated test without fix

fix: failed verification if customData is object

---

lib/api.js
test/client.js

Sign TX if `.signatures` is empty

sign if signatures are empty

---

lib/api.js
test/client.js

Fixes https://github.com/bitpay/copay/issues/4147

Decrypt copayer name in transaction proposal actions

---

lib/api.js
package.json
test/client.js

Need https://github.com/bitpay/bitcore-wallet-service/pull/589

Return note after edition

---

README.md
lib/api.js
lib/log.js
test/client.js
test/log.js

allow silencing of the logs and make silent the default log level

---

lib/errors/spec.js
test/client.js

Copay consumes these error messages and in many cases presents them directly to the UI.  These updates make the messages a bit more friendly.

Update error messages to be more UI friendly.

---

lib/credentials.js
package.json
test/client.js
test/credentials.js

+ v5.1.1
+ update bitcore-lib @ 0.14.0
+ update BWS @ 1.15.0

Fix derivation

---

.travis.yml
lib/api.js
lib/common/utils.js
lib/credentials.js
lib/verifier.js
package.json
test/client.js
test/credentials.js
test/utils.js

Support Bitcoin Cash

---

lib/api.js
package-lock.json
package.json

broadcast tx even paypros payment fails
